#!/bin/bash
echo "################################"
echo "   Authorized Keys Manager"
echo "################################"
echo

keys=(
    'swav:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClaC/Ioi1zfDoYh3ycGXnW0v4p7qhRXOPUw5ml40Ed5qIVavCwIlXMgkKx8C25nEP2qglxgP1VgMk86Qk+a12gRL4PbA3NMExRL1CtX8b+cF1SWdpo9Ua3DA6/94RBkIyz1qqFzdXg0e8cXAQUfqN4uMItsqkKkhhaF8SnteOVQPBBWONnHcz0q7FlwSyBricVnX4yblXL4ZrOZ1SdCtg0ZJk74ZG7C4vuJKSMM6RKDkprz+Jb/q20YX8O/meDhKjhby+edLQlC1csuzYLgHiHMTZ9XO67C8O6RfUVJOENkiUBzpnvBKkwAPyngGvTBAgHmGAR2G2XYCpaakMJWly9 swdowka@intellicentrics.com'
    'cleary:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Z4lrmIXe9wWPSukPdXgqPR6FgZKSr/pSTspOC2+z6BfZnd/BpBeCLIzg9EJ2nsPqYBzcB2naN4uXhAqS45h04RFiFNbL+EYRx2Xrdko58MeDfpaTja1KrqV7vf4anFFybteG7OofVOYTDWAOA3TJjmzD/XqRWSUzFROGbMyfD0hB/Bm54eYlL7yr80nKk39Fn0Hu37cvo8WHmRa0Tip7PAZ4kjGFmBdQcyYZvbIyNwvOPObS82Mkxytb4LVKXVse8CM45Q89ckFmzsWAzO5fgI2pYkjj17tqDJcjBJPJOeBwrlbReIa6rc1IekYz0wWE84ZzR7sQxyvBtAucTreT jcleary@intellicentrics.com'
)


while [ true ]; do
  line_no=0
  for i in "${keys[@]}"
  do
   name=${i%:*}
   ssh_key=${i##*:}

   if grep -Fxq "$ssh_key" ~/.ssh/authorized_keys
   then
    installed='[installed]'
   else
    installed=''
   fi

   echo "$line_no : $name $installed"
   ((line_no=+1))
  done

  printf '%s\n' "${installed_keys[@]}"

  echo
  echo "Which key would you like to add/remove from ~/.ssh/authorized_keys (q to quit) ?"
  read key_no
  echo

  if [ "$key_no" == "q" ]
  then
    exit
  else
    i=${keys[$key_no]}
    name=${i%:*}
    ssh_key=${i##*:}
    if grep -Fxq "$ssh_key" ~/.ssh/authorized_keys
    then      
      echo "Removing #name"
      grep -v "$ssh_key" ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp
      cat ~/.ssh/authorized_keys.tmp > ~/.ssh/authorized_keys
      rm ~/.ssh/authorized_keys.tmp
    else
      echo "Adding #name"
      echo "$ssh_key" >> ~/.ssh/authorized_keys
    fi
  fi
done






#echo ${keys[$key_no]}





