#!/usr/bin/env bash

# To use this on a server, run the following:
#   bash <(curl -s https://raw.githubusercontent.com/jcleary/Sandbox/master/key_add)
#

key_adder()
{
  echo "################################"
  echo "   Authorized Keys Manager"
  echo "################################"
  echo

  keys=(
      'swav:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClaC/Ioi1zfDoYh3ycGXnW0v4p7qhRXOPUw5ml40Ed5qIVavCwIlXMgkKx8C25nEP2qglxgP1VgMk86Qk+a12gRL4PbA3NMExRL1CtX8b+cF1SWdpo9Ua3DA6/94RBkIyz1qqFzdXg0e8cXAQUfqN4uMItsqkKkhhaF8SnteOVQPBBWONnHcz0q7FlwSyBricVnX4yblXL4ZrOZ1SdCtg0ZJk74ZG7C4vuJKSMM6RKDkprz+Jb/q20YX8O/meDhKjhby+edLQlC1csuzYLgHiHMTZ9XO67C8O6RfUVJOENkiUBzpnvBKkwAPyngGvTBAgHmGAR2G2XYCpaakMJWly9 swdowka@intellicentrics.com'
      'cleary:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Z4lrmIXe9wWPSukPdXgqPR6FgZKSr/pSTspOC2+z6BfZnd/BpBeCLIzg9EJ2nsPqYBzcB2naN4uXhAqS45h04RFiFNbL+EYRx2Xrdko58MeDfpaTja1KrqV7vf4anFFybteG7OofVOYTDWAOA3TJjmzD/XqRWSUzFROGbMyfD0hB/Bm54eYlL7yr80nKk39Fn0Hu37cvo8WHmRa0Tip7PAZ4kjGFmBdQcyYZvbIyNwvOPObS82Mkxytb4LVKXVse8CM45Q89ckFmzsWAzO5fgI2pYkjj17tqDJcjBJPJOeBwrlbReIa6rc1IekYz0wWE84ZzR7sQxyvBtAucTreT jcleary@intellicentrics.com'
      'hassan:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVD6e09AtA9FZfCZLKKgY5Fv/XUkmdcqSO7vJiOt5VxM/+hBj9MZXj7oaoGPEuzZHxwtNYchz8Y8yXjA9vDDlf0kKtCovMMslJYBRK5juoibYJLoapqSwQUyVKeWpgYlo1CY48sCzPo6AydQR81cSCBxzn+y/pkVQ5AOsdZcn+IT/ZJqukCrGXEa3oAKudNHxOf+QsBtKjW+RR3fBzircUMlnd+sozeJVhOwhAMK8mj/cqk24PyLSrnL6tBXY8Bx06juAdCdXFW+g9FARf0/gSDdmLXo5XZ81ViCFbJM81EXOjU0t0mGqblFhRk6RH3Pc3a4kb+XzeUvdjEC/c4iUn hkhalid@intellicentrics.com'
      'emba:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD52M2r9fPQbvl6Ww8oJlfY501/2MUi2aQz4YjgkGqTkrRnHtECYZpA9HCKbVWeTYmUNICOAWy0MDrfLo+1sFZmV7EwOe8QvWv9RhEQ0+ePMj98O+xpg0+z/JdVeWAavVLcE4lh3qa7S8TalQgARx/or4DtqUo/9Cy2cyvpfiLYHPg8bAlMJPRmgOmF9//I4arBIqeUa0ife+jUYzZcuO1LxU6s9M7MrAXXOnahavpfPCVSo4GuQnX2QJAYfXsasRuVmsx3OlMXBSZPjhRHaC+LHzfzzFCdG2NN5dGFMq+xdB8pwLmhDtev3a4ho0qYI0THPXs0IX6wQzPZqnNkVzh embasbm@gmail.com'
      'adeel:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI4aCFLmggh6wiMLVZ4gqEEGSNEjqCT4VszlVMvHdXeqZtI96NUdd75CilZS+bxnHr5N3XFXKksdpysnVFqXK2Uva4KQwLRMezmV7dY56PhX+iAh+qKhfLZx9jeW92kPN/k9KKm3d7zhusNOoqVGCiFbiKPwgZBLRAnvGMlOr85kbWR9OeOSqvPpSz6fv/M23EzWLdSyP3xRpKeoAUK8SAWvYyrWRaCETV4CVng20gQPuA3Uy6ry0sVILnjzpX7qsDM70jprvncfWJ5GKitKD7MdfhH/E5KaoY+XegOSN1JLLhoBtB3MBlsUK5xVoXhDhp3yyL3NFD8G3iWm0jj+f3 aejaz@intellicentrics.com'
      'mike:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIdw/6RKsvLqDmjPbqi7XRTzVXbug2I5uiex7CkhZbC0MzA7N/v85eriaTx1YIPXYWFz0/050gvJkFMVouMWpU54DjixQwKK4kr+Gi61N0Ok341PsudRAu5w41V6FXgm5S7YbtfuxcVhXjHcxtP+cPDfV5MRMX2QEdHmAo7fJN/NUCTkimEyzGuhujQopPomY4a7V4bycKuZod9k1q9yPxcBeb7lOGUCHJylbLgty1I5pSBeNgBBK/qhAdtVloEc/2k315itRX24KOZTDUWNJUQfBC3dz/JzBi1i5B+CY9t1DetiMwkJgdk4pDSlXi7KipB2BwOKyYeZQRFGhJyFyn michaelgriffiths@Michaels-MacBook-Pro.local'
      'squires:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9U+itYeuKn1T/oIC0Gyk8h9fldD0FTjI2YZtyn11NwLH3EEBiKlYnarV3XsL9jOetVuq/dEC6fl5Oply0u4fDnXe10PcEUV4KffeeVFQmeW+QUSMApHbzds8ErJrZ0IXcg3Saxhcu1Qlg6rFbFWL7JoK9LV0HGbi6S1RZR6U/xX4kqYRtrij/rTP2TicEhHA3ho54Z9ILgT7tf2dSXesnANmAPsA/64pk9lV8WnA6vJEWoBY4bcrIOIwAGT52lm9jyaABuqS6iGLNu1VvOFSQ5YPFMpDUs/+8LLtbQ/Ejxnu/BP8mivkinmzjAv+fR8xGJLWkL9P7UZ2/tleGKBWF jsquires@intellicentrics.com'
      'carter:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI5mg0JR9lQujPoGHQMilI9Zieq56Cu0QJh1XvV45pdsT/QkFsAbx5OCOGeUnHWWIwAGgG4XDKFYyCMOrAezbHNc+uyaGpk4+AltJLiu/xUvR1+aiFQ50aMXwP7tQ9ZQvkGDWKokPDwjlkiW4lYSvHlAR+jqwvAXuwqXd6U1VQtpXsQEBq5Urx34p9Rrhjn6wGeQlWCeZfsZn9ognAOqSWUKW8bskaK2+YlFSd1RIlbwJtya1GgBGONIGZQ6ucM8uLTQKyey6qvSBjlmEBY6lCmWxyt/psdPxSvij3F38kCZPkxzhk+/MZxX+ouZDMhgvhrCWTu2vUk0E9Pug5mFg/ jcarter@intellicentrics.com'
  )

  while [ true ]; do
    line_no=0
    for i in "${keys[@]}"
    do
     name=${i%:*}
     ssh_key=${i##*:}

     if grep -Fxq "$ssh_key" ~/.ssh/authorized_keys
     then
      is_installed='[installed]'
     else
      is_installed=''
     fi

     echo "$line_no : $name $is_installed"
     ((line_no+=1))
    done

    printf '%s\n' "${installed_keys[@]}"

    echo
    echo "Which key would you like to add/remove from ~/.ssh/authorized_keys (q to quit) ?"
    read key_no

    if [ "$key_no" == "q" ]
    then
      exit 0
    else
      i=${keys[$key_no]}
      name=${i%:*}
      ssh_key=${i##*:}
      if grep -Fxq "$ssh_key" ~/.ssh/authorized_keys
      then      
        echo "Removing $name"
        grep -v "$ssh_key" ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp
        cat ~/.ssh/authorized_keys.tmp > ~/.ssh/authorized_keys
        rm ~/.ssh/authorized_keys.tmp
      else
        echo "Adding $name"
        echo "$ssh_key" >> ~/.ssh/authorized_keys
      fi
    fi
    echo
  done
}

key_adder 

